### ISSUE TITLE
warning: "__SSE2__" redefined

### ISSUE THREAD

**Issue by Yatima1460** [recp/cglm#48] opened 2018-04-30 02:53 UTC
It would be nice to not define **\_\_SSE2__** if it's already defined, otherwise the log would fill of warnings:
_"warning: "\_\_SSE2\_\_" redefined"_ for every include of cglm.h.
Mingw-w64 x86_64-7.2.0-posix-seh-rt_v5-rev1 already defines it.
Thanks.

**Comment by luluco250** [comment] 2018-04-30 15:17
@recp I was only able to compile cglm under MSVC by commenting out the `CGLM_EXPORT` macro.

The problem is that it is illegal in MSVC to declare a function as `__declspec(dllimport)`, which clgm does for what seems to be all of it's functions. For example, this function from `affine.c`:

```c
CGLM_EXPORT
void
glmc_translate_make(mat4 m, vec3 v) {
  glm_translate_make(m, v);
}
```

Breaks for me in Visual Studio 2017, because it's declaring the function as `__declspec(dllimport)` (when `CGLM_DLL` is defined). This is a case where it should be something like (with the macro expanded):

```c
__declspec(dllimport)
void
glmc_translate_make(mat4, vec3);
```

Not sure if this would fix it, but as I mentioned I got the project to compile by commenting out the macro in `common.h`:

```c
#if defined(_WIN32)
#  ifdef CGLM_DLL
#    define CGLM_EXPORT __declspec(dllexport)
#  else
#    define CGLM_EXPORT /*__declspec(dllimport)*/
#  endif
#  define CGLM_INLINE __forceinline
#else
#  define CGLM_EXPORT __attribute__((visibility("default")))
#  define CGLM_INLINE static inline __attribute((always_inline))
#endif
```

This could have repercussions however, I was not able to test it yet.

**Comment by recp** [comment] 2018-04-30 16:11
@Yatima1460 thanks, it is merged!

Would it be possible to setup mingw build on AppVeyor CI as parallel to msvc build, any ideas?

**Closed** 2018-05-10 14:01 UTC
