### ISSUE TITLE
Strange behavior glm_lookat

### ISSUE THREAD

**Issue by Yatima1460** [recp/cglm#54] opened 2018-05-09 16:33 UTC
I am adding a map editing mode, so the camera will look down on the world

These two versions work perfectly:

glm_lookat((vec3){100,30,100},(vec3){100,0,100.1},WORLD_VECTOR_UP,camera_view_matrix);
glm_lookat((vec3){100,30,100},(vec3){100,0,99.9},WORLD_VECTOR_UP,camera_view_matrix);

The output of 100.1 is:

Matrix (float4x4):
	|-1.0000	0.0000	0.0000	100.0000|
	|0.0000	0.0033	1.0000	-100.0994|
	|-0.0000	1.0000	-0.0033	-29.6665|
	|0.0000	0.0000	0.0000	1.0000|

But when I try to look **exactly down** from an altitude of 30:
glm_lookat((vec3){100,30,100},(vec3){100,0,100},WORLD_VECTOR_UP,camera_view_matrix);

The output is:

Matrix (float4x4):
	|0.0000	0.0000	0.0000	-0.0000|
	|0.0000	0.0000	-0.0000	-0.0000|
	|-0.0000	1.0000	-0.0000	-30.0000|
	|0.0000	0.0000	0.0000	1.0000|

And it obviously doesn't render anymore.
Is it expected behavior and I am missing something or is it a bug?

**Comment by recp** [comment] 2018-05-09 20:43
What is **WORLD_VECTOR_UP** value? If it is standard value like Y_UP or Z_UP then you can use GLM_YUP, GLM_ZUP and GLM_XUP for this purpose. 

I assume WORLD_VECTOR_UP is `0, 1, 0`,

`glm_lookat` uses a cross product of `center - target`, so in your case `center - target` yields UP vector direction. cross product of same direction or parallel vectors yields ZERO vector. In this case view matrix will be wrong. Because view matrix will be built on the ZERO vector.

100,30,100 - 100,0,100 = 0,30,0 -> normalize(0,30,0) == 0, 1, 0 == Y_UP

A note from: https://www.khronos.org/registry/OpenGL-Refpages/gl2.1/xhtml/gluLookAt.xml
> The UP vector must not be parallel to the line of sight from the eye point to the reference point.

**So look direction should not be same direction or parallel to UP vector.** We must add this note to docs.

If you look down to map then you could use Z_UP or X_UPinstead of Y_UP, would it be a problem? Could you test it?

Another Alternatives:
0- Probably changing UP vector will fix your view matrix
1- `glm_look`: This is similar to glm_lookat but it uses direction instead of target vector. This doesn't solve your problem with given UP vector of course
2- `glm_look_anyup(vec3 eye, vec3 dir, mat4 dest)`: This is wrapper for `glm_look` but it generates UP vector for you. Maybe you could test this for your case?
3- `glm_quat_look(vec3 eye, versor ori, mat4 dest)`: This is really cool function :) It creates view matrix using quaternion.

**Comment by recp** [comment] 2018-05-29 08:33
@Yatima1460 Did that help you fix your issue? Or if you already fixed that issue, maybe sharing solution would help to others :) 

Also I added a note about up vector (copy-pasted from OpenGL docs): https://github.com/recp/cglm/commit/af812e86ebc06aca69d27a058bcd6e5d4ec52923

We can close this issue if the issue is not present anymore?

**Comment by Yatima1460** [comment] 2018-05-30 05:11
Oh yes anyup would have fixed it (I don't need this code anymore), the real issue here was the missing documentation.

Those edge cases should always be documented, I will let you know if I will find any other ones without doc strings.

Thanks

**Comment by recp** [comment] 2018-05-30 08:10
@Yatima1460 thank you 🤗

**Closed by recp** 2018-05-30 08:10 UTC
